type Query {
  """
  Fetch a comment by its id
  """
  comment(id: ID!): Comment

  """
  Fetch a list of comments
  """
  comments(
    first: Int
    after: ID
    last: Int
    before: ID
    orderBy: String = "id"
    direction: ORDER = ASC
    deleted: Boolean = false
  ): CommentConnection
}

type CommentConnection {
  pageInfo: PageInfo!
  edges: [CommentEdge]!
  total: Int
}

type CommentEdge {
  node: Comment!
  cursor: String!
}
