type Query {
  """
  Fetch an organization by its id
  """
  organization(id: ID!): Organization

  """
  Fetch a list of organizations
  """
  organizations(
    search: String
    page: Int = 1
    limit: Int = 10
    orderBy: String = "id"
    direction: ORDER = ASC
    deleted: Boolean = false
  ): [Organization!]
}
