type Query {
  """
  Fetch a user by his id
  """
  user(id: ID!): User

  """
  Fetch a list of users
  """
  users(
    page: Int = 1
    limit: Int = 10
    orderBy: String = "id"
    direction: ORDER = ASC
    deleted: Boolean = false
  ): [User!]
}
