"""
A comment created by a user
"""
type Comment {
  """
  The identifier
  """
  id: ID!
  """
  The comment itself
  """
  body: String!
  """
  The date it was created in ISO8601 format
  """
  createdAt: Date!
  """
  The date it was last updated in ISO8601 format
  """
  updatedAt: Date!
  """
  The date it was soft deleted in ISO8601 format
  """
  deletedAt: Date
  """
  The user who wrote the comment
  """
  author: User!
  """
  The thread to which it belongs
  """
  issue: Issue
  """
  The comment that is being answered
  """
  parent: Comment
  """
  Comments that respond to this comment
  """
  children: [Comment!]
}
