# Objects

"""
The result of a mutation or query
"""
type Operation {
  """
  The operation was completed or not
  """
  status: Boolean!
  """
  A message describing the operation result
  """
  message: String!
}

# Enums

"""
The sort direction
"""
enum ORDER {
  """
  Ascending
  """
  ASC
  """
  Descending
  """
  DESC
}
