"""
A thread created by a user
"""
type Issue {
  """
  The identifier
  """
  id: ID!
  """
  The title of the issue
  """
  title: String!
  """
  The detailed explanation of the issue
  """
  body: String!
  """
  The date it was created in ISO8601 format
  """
  createdAt: Date!
  """
  The date it was last updated in ISO8601 format
  """
  updatedAt: Date!
  """
  The user who started the thread
  """
  author: User!
  """
  The product that is discussed in the issue
  """
  product: Product!
  """
  The comments made by users
  """
  comments: [Comment!]
}

type Query {
  """
  Fetch an issue by its id
  """
  issue(id: ID!): Issue

  """
  Fetch a list of issues
  """
  issues(
    page: Int = 1
    limit: Int = 10
    orderBy: String = "id"
    direction: ORDER = ASC
  ): [Issue!]
}

type Mutation {
  """
  Create a new issue
  """
  createIssue(issue: CreateIssueInput!): IssuePayload

  """
  Update an existing issue
  """
  updateIssue(id: ID!, issue: UpdateIssueInput!): IssuePayload

  """
  Delete an existing issue
  """
  deleteIssue(id: ID!): DeleteIssuePayload
}

"""
The possible validation errors returned when creating or updating an issue
"""
type IssueValidation {
  """
  The validation error of the title
  """
  title: String
  """
  The validation error of the body
  """
  body: String
  """
  The validation error of the user's identifier
  """
  userId: String
  """
  The validation error of the product's identifier
  """
  productId: String
}

"""
The payload returned when a new issue is created or updated
"""
type IssuePayload {
  """
  The status of the operation
  """
  operation: Operation!
  """
  The created or updated issue
  """
  issue: Issue
  """
  The validation errors
  """
  errors: IssueValidation
}

"""
The payload returned when an issue is deleted
"""
type DeleteIssuePayload {
  """
  The status of the operation
  """
  operation: Operation!
  """
  The deleted issue
  """
  issue: Issue
}

"""
The properties needed to create a new issue
"""
input CreateIssueInput {
  """
  The title
  """
  title: String!
  """
  The body
  """
  body: String!
  """
  The user's identifier
  """
  userId: String!
  """
  The product's identifier
  """
  productId: String!
}

"""
The properties needed to update an existing issue
"""
input UpdateIssueInput {
  """
  The title
  """
  title: String
  """
  The body
  """
  body: String
  """
  The user's identifier
  """
  userId: String
  """
  The product's identifier
  """
  productId: String
}
