"""
A thread created by a user
"""
type Issue {
  """
  The identifier
  """
  id: ID!
  """
  The title of the issue
  """
  title: String!
  """
  The detailed explanation of the issue
  """
  body: String!
  """
  The date it was created in ISO8601 format
  """
  createdAt: Date!
  """
  The date it was last updated in ISO8601 format
  """
  updatedAt: Date!
  """
  The date it was soft deleted in ISO8601 format
  """
  deletedAt: Date
  """
  The user who started the thread
  """
  author: User!
  """
  The product that is discussed in the issue
  """
  product: Product!
  """
  The comments made by users
  """
  comments: [Comment!]
}
