type Query {
  """
  Fetch a list of products
  """
  products(
    page: Int = 1
    limit: Int = 10
    orderBy: String = "id"
    direction: ORDER = ASC
    deleted: Boolean = false
  ): [Product!]
}
