"""
A product or a service
"""
type Product {
  """
  The identifier
  """
  id: ID!
  """
  The name. Eg. Model S
  """
  name: String!
  """
  The description. Eg. High-end electric liftback
  """
  description: String
  """
  The date it was created in ISO8601 format
  """
  createdAt: Date!
  """
  The date it was last updated in ISO8601 format
  """
  updatedAt: Date!
  """
  The date it was soft deleted in ISO8601 format
  """
  deletedAt: Date
  """
  The user or organization that owns the product
  """
  owner: ProductOwner!
  """
  The issues of the product
  """
  issues: [Issue!]
}

type Query {
  """
  Fetch a product by its id
  """
  product(id: ID!): Product

  """
  Fetch a list of products
  """
  products(
    page: Int = 1
    limit: Int = 10
    orderBy: String = "id"
    direction: ORDER = ASC
  ): [Product!]
}

type Mutation {
  """
  Create a new product
  """
  createProduct(product: CreateProductInput!): ProductPayload

  """
  Update an existing product
  """
  updateProduct(id: ID!, product: UpdateProductInput!): ProductPayload

  """
  Delete an existing product
  """
  deleteProduct(id: ID!): SimpleProductPayload

  """
  Restore a deleted product
  """
  restoreProduct(id: ID!): SimpleProductPayload
}

"""
The possible validation errors returned when creating or updating a product
"""
type ProductValidation {
  """
  The validation error of the name
  """
  name: String
  """
  The validation error of the description
  """
  description: String
  """
  The validation error of the owner's identifier
  """
  ownerId: String
}

"""
The payload returned when a new product is created or updated
"""
type ProductPayload {
  """
  The status of the operation
  """
  operation: Operation!
  """
  The created or updated product
  """
  product: Product
  """
  The validation errors
  """
  errors: ProductValidation
}

"""
The payload returned when a product is deleted or restored
"""
type SimpleProductPayload {
  """
  The status of the operation
  """
  operation: Operation!
  """
  The product
  """
  product: Product
}

"""
The properties needed to create a new product
"""
input CreateProductInput {
  """
  The name
  """
  name: String!
  """
  The description
  """
  description: String
  """
  The owner's identifier
  """
  ownerId: ID!
}

"""
The properties used to update an existing product
"""
input UpdateProductInput {
  """
  The name
  """
  name: String
  """
  The description
  """
  description: String
  """
  The owner's identifier
  """
  ownerId: ID
}
