"""
An organization. Eg. a company
"""
type Organization {
  """
  The identifier
  """
  id: ID!
  """
  The name. Eg. Tesla Motors
  """
  name: String!
  """
  The main activity. Eg. Manufacturer of electric vehicles
  """
  bio: String
  """
  The date it was created in ISO8601 format
  """
  createdAt: Date!
  """
  The date it was last updated in ISO8601 format
  """
  updatedAt: Date!
  """
  The date it was soft deleted in ISO8601 format
  """
  deletedAt: Date
  """
  The products or services that belong to the organization
  """
  products: [Product!]
  """
  Users who are members of the organization
  """
  members: [User!]
}
