type Query {
  """
  Fetch a product by its id
  """
  product(id: ID!): Product

  """
  Fetch a list of products
  """
  products(
    search: String
    page: Int = 1
    limit: Int = 10
    orderBy: String = "id"
    direction: ORDER = ASC
    deleted: Boolean = false
  ): [Product!]
}
