"""
A comment created by a user
"""
type Comment {
  """
  The identifier
  """
  id: ID!
  """
  The comment itself
  """
  body: String!
  """
  The date it was created in ISO8601 format
  """
  createdAt: Date!
  """
  The date it was last updated in ISO8601 format
  """
  updatedAt: Date!
  """
  The user who wrote the comment
  """
  author: User!
  """
  The thread to which it belongs
  """
  issue: Issue
  """
  The comment that is being answered
  """
  parent: Comment
  """
  Comments that respond to this comment
  """
  children: [Comment!]
}

type Query {
  """
  Fetch a comment by its id
  """
  comment(id: ID!): Comment

  """
  Fetch a list of comments
  """
  comments(
    page: Int = 1
    limit: Int = 10
    orderBy: String = "id"
    direction: ORDER = ASC
  ): [Comment!]
}

type Mutation {
  """
  Create a new comment
  """
  createComment(comment: CreateCommentInput!): CommentPayload
}

"""
The possible validation errors returned when creating or updating a comment
"""
type CommentValidation {
  """
  The validation error of the body
  """
  body: String
  """
  The validation error of the author's identifier
  """
  userId: String
  """
  The validation error of the issue's identifier
  """
  issueId: String
  """
  The validation error of the parent's identifier
  """
  parentId: String
}

"""
The payload returned when a new comment is created or updated
"""
type CommentPayload {
  """
  The status of the operation
  """
  operation: Operation!
  """
  The created or updated comment
  """
  comment: Comment
  """
  The validation errors
  """
  errors: CommentValidation
}

"""
The properties needed to create a new comment
"""
input CreateCommentInput {
  """
  The body
  """
  body: String!
  """
  The author identifier
  """
  userId: ID!
  """
  The issue identifier
  """
  issueId: ID!
  """
  The parent identifier
  """
  parentId: ID
}
