"""
A comment created by a user
"""
type Comment {
  """
  The identifier
  """
  id: ID!
  """
  The comment itself
  """
  body: String!
  """
  The date it was created in ISO8601 format
  """
  createdAt: Date!
  """
  The date it was last updated in ISO8601 format
  """
  updatedAt: Date!
  """
  The date it was soft deleted in ISO8601 format
  """
  deletedAt: Date
  """
  The user who wrote the comment
  """
  author: User!
  """
  The thread to which it belongs
  """
  issue: Issue
  """
  The comment that is being answered
  """
  parent: Comment
  """
  Comments that respond to this comment
  """
  children: [Comment!]
}

type Query {
  """
  Fetch a comment by its id
  """
  comment(id: ID!): Comment

  """
  Fetch a list of comments
  """
  comments(
    page: Int = 1
    limit: Int = 10
    orderBy: String = "id"
    direction: ORDER = ASC
  ): [Comment!]
}

type Mutation {
  """
  Create a new comment
  """
  createComment(comment: CreateCommentInput!): CreateCommentPayload

  """
  Update an existing comment
  """
  updateComment(id: ID!, comment: UpdateCommentInput!): UpdateCommentPayload

  """
  Delete an existing comment
  """
  deleteComment(id: ID!): SimpleCommentPayload

  """
  Restore a deleted comment
  """
  restoreComment(id: ID!): SimpleCommentPayload
}

"""
The possible validation errors returned when creating a comment
"""
type CreateCommentValidation {
  """
  The validation error of the body
  """
  body: String
  """
  The validation error of the author's identifier
  """
  userId: String
  """
  The validation error of the issue's identifier
  """
  issueId: String
  """
  The validation error of the parent's identifier
  """
  parentId: String
}

"""
The payload returned when a new comment is created
"""
type CreateCommentPayload {
  """
  The status of the operation
  """
  operation: Operation!
  """
  The created comment
  """
  comment: Comment
  """
  The validation errors
  """
  errors: CreateCommentValidation
}

"""
The possible validation errors returned when updating a comment
"""
type UpdateCommentValidation {
  """
  The validation error of the body
  """
  body: String
}

"""
The payload returned when a comment is updated
"""
type UpdateCommentPayload {
  """
  The status of the operation
  """
  operation: Operation!
  """
  The updated comment
  """
  comment: Comment
  """
  The validation errors
  """
  errors: UpdateCommentValidation
}

"""
The payload returned when a comment is deleted or restored
"""
type SimpleCommentPayload {
  """
  The status of the operation
  """
  operation: Operation!
  """
  The comment
  """
  comment: Comment
}

"""
The properties needed to create a new comment
"""
input CreateCommentInput {
  """
  The body
  """
  body: String!
  """
  The author identifier
  """
  userId: ID!
  """
  The issue identifier
  """
  issueId: ID!
  """
  The parent identifier
  """
  parentId: ID
}

"""
The properties used to update an existing comment
"""
input UpdateCommentInput {
  """
  The body
  """
  body: String!
}
